apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: infra
  name: mariadb-infra
  labels:
    type: local
    app: mariadb-infra
spec:
  storageClassName: local-storage
  capacity:
    storage: 350Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/db/mariadb-infra/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infra
  name: mariadb-pvc-infra
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 350Mi
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: mariadb-infra
  labels:
    app: mariadb-infra
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb-infra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-infra
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-infra
  serviceName: mariadb-headless
  template:
    metadata:
      labels:
        app: mariadb-infra
    spec:
      containers:
      - name: mariadb-infra
        image: mariadb:10.11
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret-infra
              key: MYSQL_RANDOM_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-secret-infra
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret-infra
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret-infra
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mariadb-infra
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "145Mi"
            cpu: "25m"
          limits:
            memory: "180Mi"
            cpu: "160m"
      volumes:
      - name: mariadb-infra
        persistentVolumeClaim:
          claimName: mariadb-pvc-infra
