
pipeline {
    agent {
        kubernetes {
            defaultContainer 'docker'
            yaml """
apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
    - name: docker
      image: twnsnd2team/docker:v2
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
      command:
        - sleep
        - "1d"
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
          readOnly: false
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: kubeconfig
      secret:
        secretName: jenkins-agent
                """
        }
    }
   environment {
    APP_ENV = 'finance-dev'
    IMAGE_BASE = 'freenance/postgres'
    IMAGE_TAG = "v$BUILD_NUMBER"
    IMAGE_NAME = "${env.IMAGE_BASE}"
    IMAGE_NAME_LATEST = "${env.IMAGE_BASE}:latest"
    DOCKERFILE_NAME = "Dockerfile"
    NAMESPACE = 'finance-dev'
    }
    options {
        timeout(time: 10, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    
    stages {
        stage('Delete workspace before build starts') {
            steps {
                echo 'Deleting workspace'
                deleteDir()
            }
        }
    stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'git_freenance', url: 'git@github.com:PineappleIncTeam/postgres_master.git'
                script {
                    commitId = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
                    currentBuild.description = "${commitId}"
                    echo "${commitId}"
                }
            }
        }
    stage('build & push image') {
        steps {
            script {
                def dockerImage = docker.build("${env.IMAGE_NAME}:${commitId}","-f ${env.DOCKERFILE_NAME} .")
                    docker.withRegistry('', 'docker-hub-freenance') {
                    dockerImage.push()
                    }     
                echo "Pushed Docker Image: ${env.IMAGE_NAME}:${commitId}"
                }
                  sh "docker rmi ${env.IMAGE_NAME}:${commitId}"
            }
        }
    }
            
         stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'kubernetes-jenkins']) {
                    sh "sed -i 's/{{NAMESPACE}}/${NAMESPACE}/g' postgres-master-manifest.yaml"
                    sh "sed -i 's/{{IMAGE_TAG}}/${commitId}/g' postgres-master-manifest.yaml"
                    sh 'kubectl apply -f postgres-master-manifest.yaml'
                }
            }
        }
    }
    
 