apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: finance-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis
        image: redis:7.4.2
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 50m
            memory: 20Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: finance-prod
spec:
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  selector:
    app: redis-service
  type: ClusterIP
